language: rust
rust:
  - nightly
addons:
    apt:
        packages:
            - libssl-dev

cache: cargo

before_script:
 - cargo install cargo-tarpaulin

script:
 - cargo clean
 - cargo build
 - cargo test --features burkardt

after_success:
 - cargo tarpaulin --ignore-tests --features burkardt --out Xml
 - bash <(curl -s https://codecov.io/bash) 

