language: rust
rust:
  - nightly
addons:
    apt:
        packages:
            - libssl-dev

cache: cargo

before_script:
 - cargo install cargo-tarpaulin
 - set -e

script:
 - cargo clean
 - cargo build
 - cargo test
 - cargo test --package rust-lp --all-features --release --test mod

after_success:
 - cargo tarpaulin --ignore-tests --features burkardt unicamp --out Xml
 - bash <(curl -s https://codecov.io/bash) 

