[package]
name = "rust-lp"
version = "0.0.3"
authors = ["Bram van den Heuvel <bram@vandenheuvel.online>"]
license = "MIT"
repository = "https://github.com/vandenheuvel/rust-lp"
description = "A solver for linear programs"

edition = "2018"

[dependencies]
num = "0.3.1"
daggy = "0.7.0"  # Currently only for debug asserts

itertools = "0.9.0"

clap = { version = "3.0.0-beta.2", optional = true }

[features]
burkardt = []
miplib = []
netlib = []
unicamp = []
binaries = ["clap"]

[profile.release]
lto = true

[[bin]]
name = "rust-lp"
path = "src/bin/main.rs"
required-features = ["binaries"]
